version: "3.8"
services:
  api:
    container_name: api
    platform: linux/amd64
    build:
      context: ./backend/
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - ./backend/vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    platform: linux/amd64
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - dbvol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db
volumes:
  dbvol: